export const data = {
    letters : [{
        letter: 'ﺍ',
        nom: 'Alif',
        fin:  'ـﺎ',
        milieu: 'ـﺎـ',
        début: 'ﺍـ',
        voyelles: [  "إِ",  "أُ", "أَ"],
        voyellesound: ['./i.mp3', './o.mp3', './aa.mp3'],
        id: 'lettre-1',
        path: './alif.mp3'
      },
      {
        letter: 'ﺏ',
        nom: 'ba',
        fin:  'ـﺐ',
        milieu: 'ـﺎـ',
        début: 'ﺍـ',
        voyelles: ["بِ","بُ", "بَ"],
        voyellesound: ['./bi.mp3', './bo.mp3', './baaaa.mp3'],
        id: 'lettre-2',
        path: './ba.mp3'
      },
      {
        letter: 'ﺕ',
        nom: 'ta',
        fin:  'ـﺖ',
        milieu: 'ـﺘـ',
        début: 'ﺗـ',
        voyelles: [ "تِ ", "تُ", " تَ"],
        voyellesound: ['./ti.mp3', './tou.mp3', './tata.mp3'],
        id: 'lettre-3',
        path: './ta.mp3'
      },
      {
        letter: 'ﺙ',
        nom: 'Tha',
        fin:  'ـﺚ',
        milieu: 'ـﺜـ',
        début: 'ﺛـ',
        voyelles: [ "ثِ","ثُ", "ثَ"],
        voyellesound: ['./thi.mp3', './thou.mp3', './tthhha.mp3'],
        id: 'lettre-4',
        path: 'tha.mp3'
      },
      {
        letter: 'ﺝ',
        nom: 'Jim',
        fin:  'ـﺞ',
        milieu: 'ـﺠـ',
        début: 'ﺟـ',
        voyelles: [ "جِ","جُ","جَ"],
        voyellesound: ['./ji.mp3', './jo.mp3', 'ja.mp3'],
        id: 'lettre-5',
        path: 'jim.mp3'
      },
      {
        letter: 'ﺡ',
        nom: 'Ha',
        fin:  'ـﺢ',
        milieu: 'ـﺤـ',
        début: 'ﺣـ',
        voyelles: ["حِ","حُ","حَ"],
        id: 'lettre-6',
        voyellesound: ['./7hi.mp3', './ho.mp3', './7ha.mp3'],
        path: 'ha.mp3'
      },
      {
        letter: 'ﺥ',
        nom: 'Kha',
        fin:  'ـﺦ',
        milieu: 'ـﺨـ',
        début: 'ﺧـ',
        voyelles: ["خِ","خُ","خَ"],
        voyellesound: ['./khi.mp3', './kho.mp3', './khaaa.mp3'],
        id: 'lettre-7',
        path: 'kha.mp3'
      },
      {
        letter: 'ﺩ',
        nom: 'dal',
        fin:  'ـﺪ',
        milieu: 'ـﺪـ',
        début: 'ﺩـ',
        voyelles: [ "دِ","دُ","دَ"],
        voyellesound: ['./di.mp3', './do.mp3', './daaa.mp3'],
        id: 'lettre-8',
        path: 'da.mp3'
      },
      {
        letter: 'ﺫ',
        nom: 'Dhal',
        fin:  'ـﺬ',
        milieu: 'ـﺬـ',
        début: 'ﺫـ',
        voyelles: ["ذِ", "ذُ","ذَ"],
        voyellesound: ['./dhi.mp3', './dho.mp3', './dha.mp3'],
        id: 'lettre-9',
        path: 'dhal.mp3'
      },
      {
        letter: 'ﺭ',
        nom: 'Ra',
        fin:  'ـﺮ',
        milieu: 'ـﺭـ',
        début: 'ﺭـ',
        voyelles: ["رِ", "رُ","رَ"],
        voyellesound: ['./ri.mp3', './ro.mp3', './ra.mp3'],
        id: 'lettre-10',
        path: 'rae.mp3'
      },
      {
        letter: 'ﺯ',
        nom: 'Zay',
        fin:  'ـﺰ',
        milieu: 'ـﺯـ',
        début: 'ﺯـ',
        voyelles: [ "زِ", "زُ" ,"زَ"],
        voyellesound: ['./zi.mp3', './zo.mp3', './za.mp3'],
        id: 'lettre-11',
        path: 'zin.mp3'
      },
      {
        letter: 'ﺱ',
        nom: 'Sin',
        fin:  'ـﺲ',
        milieu: 'ـﺴـ',
        début: 'ﺳـ',
        voyelles: [" سِ", "سُ","سَ"],
        voyellesound: ['./si.mp3', './so.mp3', './sa.mp3'],
        id: 'lettre-12',
        path: 'sin.mp3'
      },
      {
        letter: 'ﺵ',
        nom: 'Shin',
        fin:  'ـﺶ',
        milieu: 'ـﺸـ',
        début: 'ﺷـ',
        voyelles: [ " شِ", "شُ" ,"شَ"],
        voyellesound: ['./chi.mp3', './sho.mp3', './sha.mp3'],
        id: 'lettre-13',
        path: 'shin.mp3'
      },
      {
        letter: 'ﺹ',
        nom: 'Sad',
        fin:  'ـﺺ',
        milieu: 'ـﺼـ',
        début: 'ﺻـ',
        voyelles: ["صِ","صُ","صَ"],
        voyellesound: ['./siiii.mp3', './sooo.mp3', './saaaa.mp3'],
        id: 'lettre-14',
        path: 'sad.mp3'
      },
      {
        letter: 'ﺽ',
        nom: 'Dhad',
        fin:  'ـﺾ',
        milieu: 'ـﻀـ',
        début: 'ﺿـ',
        voyelles: ["ضِ","ضُ","ضَ"],
        voyellesound: ['./dhiiiiii.mp3', './thoooi.mp3', './dha.mp3'],
        id: 'lettre-15',
        path: 'dhad.mp3'
      },
      {
        letter: 'ﻁ',
        nom: 'Ta',
        fin:  'ﻁ',
        milieu: 'ـﻄـ',
        début: 'ﻃـ',
        voyelles: ["طِ","طُ","طَ"],
        voyellesound: ['./tiiiii.mp3', './tooo.mp3', './taaaa.mp3'],
        id: 'lettre-16',
        path: 'tae.mp3'
      },
      {
        letter: 'ﻅ',
        nom: 'Za',
        fin:  'ـﻆ',
        milieu: 'ـﻈـ',
        début: 'ﻇـ',
        voyelles: ["ظِ", "ظُ","ظَ"],
        voyellesound: ['./dhiiiiii.mp3', './thoooi.mp3', './dha.mp3'],
        id: 'lettre-17',
        path: 'dhad2.mp3'
      },
      {
        letter: 'ﻉ',
        nom: 'Ayn',
        fin:  'ـﻊ',
        milieu: 'ـﻌـ',
        début: 'ﻋـ',
        voyelles: ["عِ","عُ","عَ"],
        voyellesound: ['./3ii.mp3', './3ooo.mp3', './333aa.mp3'],
        id: 'lettre-18',
        path: 'ayn.mp3'
      },
      {
        letter: 'ﻍ',
        nom: 'Ghayn',
        fin:  'ـﻎ',
        milieu: 'ـﻐـ',
        début: 'ﻏـ',
        voyelles: ["غِ","غُ","غَ"],
        voyellesound: ['./ghiii.mp3', './ghooo.mp3', './ghaaa.mp3'],
        id: 'lettre-19',
        path: 'ghayn.mp3'
      },
      {
        letter: 'ﻑ',
        nom: 'Fa',
        fin:  'ـﻒ',
        milieu: 'ـﻔـ',
        début: 'ﻓـ',
        voyelles: ["فِ", "فُ" , "فَ"],
        voyellesound: ['./fiiii.mp3', './fooo.mp3', './faaaaa.mp3'],
        id: 'lettre-20',
        path: 'fae.mp3'
      },
      {
        letter: 'ﻕ',
        nom: 'Qaf',
        fin:  'ـﻖ',
        milieu: 'ـﻘـ',
        début: 'ﻗـ',
        voyelles: ["قِ","قُ" ," قَ"],
        voyellesound: ['./9iiii.mp3', './9ooo.mp3', './9aaa.mp3'],
        id: 'lettre-21',
        path: '9af.mp3'
      },
      {
        letter: 'ﻙ',
        nom: 'Kaf',
        fin:  'ـﻚ',
        milieu: 'ـﻜـ',
        début: 'ﻛـ',
        voyelles: ["كِ","كُ","كَ"],
        voyellesound: ['./kiiii.mp3', './kooo.mp3', './kaaa.mp3'],
        id: 'lettre-22',
        path: 'kaf.mp3'
      },
      {
        letter: 'ﻝ',
        nom: 'Lam',
        fin:  'ـﻞ',
        milieu: 'ـﻠـ',
        début: 'ﻟـ',
        voyelles: [ "لِ","لُ","لَ"],
        voyellesound: ['./liii.mp3', './looo.mp3', './la.mp3'],
        id: 'lettre-23',
        path: 'lam.mp3'
      },
      {
        letter: 'ﻡ',
        nom: 'Mim',
        fin:  'ـﻢ',
        milieu: 'ـﻤـ',
        début: 'ﻣـ',
        voyelles: ["مِ","مُ","مَ"],
        voyellesound: ['./mii.mp3', './.mp3', './maaa.mp3'],
        id: 'lettre-24',
        path: 'mim.mp3'
      },
      {
        letter: 'ﻥ',
        nom: 'Nun',
        fin:  'ـﻦ	',
        milieu: 'ـﻨـ',
        début: 'ﻧـ',
        voyelles: ["نِ" ,"نُ","نَ"],
        voyellesound: ['./nii.mp3', './nooo.mp3', './naaaa.mp3'],
        id: 'lettre-25',
        path: 'noun.mp3'
      },
      {
        letter: 'ﻩ',
        nom: 'ha',
        fin:  'ـﻪ',
        milieu: 'ـﻬـ',
        début: 'ﻫـ',
        voyelles: ["هِـ","هُـ","هَـ"],
        voyellesound: ['./hii.mp3', './ho.mp3', './haaaaa.mp3'],
        id: 'lettre-26',
        path: 'hae.mp3'
      },
      {
        letter: 'ﻭ',
        nom: 'Waw',
        fin:  'ـﻮ',
        milieu: 'ـﻭـ',
        début: 'ﻭـ',
        voyelles: [" وِ","وُ","وَ"],
        voyellesound: ['./alif.mp3', './alif.mp3', 'https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3'],
        id: 'lettre-27',
        path: 'waw.mp3'
      },
      {
        letter: 'ﻱ',
        nom: 'Ya',
        fin:  'ـﻲ',
        milieu: 'ـﻴـ',
        début: 'ﻳـ',
        voyelles: ["يِ","يُ" ,"يَ"],        
        voyellesound: ['./yi.mp3', './yo.mp3', './ya.mp3'],
        id: 'lettre-28',
        path: 'yae.mp3'
      },
      

     ]}